auth_info:
  path: "auth_info.json"
  file_type: "json"
  fields:
    - name: "username"
    - name: "token"
    - name: "domain"
ticket_field:
  path: "ticket_fields.csv"
  file_type: "csv"
  fields:
    - name: "slug"
    - name: "title"
    - name: "type"
    - name: "visible_in_portal"
      type: "bool"
    - name: "editable_in_portal"
      type: "bool"
    - name: "required_in_portal"
      type: "bool"
    - name: "description"
    - name: "raw_description"
    - name: "custom_field_options.names"
      type: "json"
    - name: "custom_field_options.values"
      type: "json"
  combinator:
    - dest: "custom_field_options"
      sources:
        - source_name: "custom_field_options.names"
          key: "name"
        - source_name: "custom_field_options.values"
          key: "value"
ticket_form:
  path: "ticket_forms.csv"
  file_type: "csv"
  fields:
    - name: "slug"
    - name: "name"
    - name: "position"
      type: "int"
    - name: "end_user_visible"
      type: "bool"
    - name: "display_name"
    - name: "ticket_field_ids"
      type: "json"
trigger:
  path: "triggers.csv"
  file_type: "csv"
  fields:
    - name: "slug"
    - name: "title"
    - name: "position"
      type: "int"
    - name: "conditions.all.fields"
      type: "json"
    - name: "conditions.all.operators"
      type: "json"
    - name: "conditions.all.values"
      type: "json"
    - name: "conditions.any.fields"
      type: "json"
    - name: "conditions.any.operators"
      type: "json"
    - name: "conditions.any.values"
      type: "json"
    - name: "actions.fields"
      type: "json"
    - name: "actions.values"
      type: "json"
  combinator:
    - dest: "conditions.all"
      sources:
        - source_name: "conditions.all.fields"
          key:         "field"
        - source_name: "conditions.all.operators"
          key:         "operator"
        - source_name: "conditions.all.values"
          key:         "value"
    - dest: "conditions.any"
      sources:
        - source_name: "conditions.any.fields"
          key:         "field"
        - source_name: "conditions.any.operators"
          key:         "operator"
        - source_name: "conditions.any.values"
          key:         "value"
    - dest: "actions"
      sources:
        - source_name: "actions.fields"
          key:         "field"
        - source_name: "actions.values"
          key:         "value"
